const translations = {
    'ua': {
        'header-title': 'Помічник для BAS',
        'btn-calc-main': 'КАЛЬКУЛЯТОР 🧮',
        'btn-func': 'Функції 🛠️',
        'btn-lang-menu': 'МОВА 🌍',
        'btn-close': 'Закрити ❌',
        'btn-calc': 'Рахувати показники 📊',
        'btn-search': 'Шукати проблеми 🔍',
        'btn-vat-tool': 'Розрахунок ПДВ (20%) 💰',
        'btn-cash-tool': 'Касовий звіт (-1%) 📝',
        'btn-acc-tool': 'Бухгалтерія (ПДВ) 📑',
        'action-button': 'Порахувати',
        'btn-back-calc': 'НАЗАД ⬅️',
        'btn-cancel-tool': 'ВІДМІНА',
        'calc-wait': 'Введіть суму'
    },
    'en': {
        'header-title': 'Helper for BAS',
        'btn-calc-main': 'CALCULATOR 🧮',
        'btn-func': 'Functions 🛠️',
        'btn-lang-menu': 'LANGUAGE 🌍',
        'btn-close': 'Close ❌',
        'btn-calc': 'Calculate metrics 📊',
        'btn-search': 'Search issues 🔍',
        'btn-vat-tool': 'VAT Calculation (20%) 💰',
        'btn-cash-tool': 'Cash Report (-1%) 📝',
        'btn-acc-tool': 'Accounting (VAT) 📑',
        'action-button': 'Calculate',
        'btn-back-calc': 'BACK ⬅️',
        'btn-cancel-tool': 'CANCEL',
        'calc-wait': 'Enter amount'
    },
    'de': {
        'header-title': 'BAS Helfer',
        'btn-calc-main': 'RECHNER 🧮',
        'btn-func': 'Funktionen 🛠️',
        'btn-lang-menu': 'SPRACHE 🌍',
        'btn-close': 'Schließen ❌',
        'btn-calc': 'Metriken berechnen 📊',
        'btn-search': 'Fehler suchen 🔍',
        'btn-vat-tool': 'MwSt. Berechnung (20%) 💰',
        'btn-cash-tool': 'Kassenbericht (-1%) 📝',
        'btn-acc-tool': 'Buchhaltung (MwSt) 📑',
        'action-button': 'Berechnen',
        'btn-back-calc': 'ZURÜCK ⬅️',
        'btn-cancel-tool': 'ABBRECHEN',
        'calc-wait': 'Betrag eingeben'
    },
    'pl': {
        'header-title': 'Pomocnik BAS',
        'btn-calc-main': 'KALKULATOR 🧮',
        'btn-func': 'Funkcje 🛠️',
        'btn-lang-menu': 'JĘZYK 🌍',
        'btn-close': 'Zamknij ❌',
        'btn-calc': 'Oblicz wskaźniki 📊',
        'btn-search': 'Szukaj problemów 🔍',
        'btn-vat-tool': 'Obliczanie VAT (20%) 💰',
        'btn-cash-tool': 'Raport kasowy (-1%) 📝',
        'btn-acc-tool': 'Księgowość (VAT) 📑',
        'action-button': 'Oblicz',
        'btn-back-calc': 'POWRÓT ⬅️',
        'btn-cancel-tool': 'ANULUJ',
        'calc-wait': 'Wpisz kwotę'
    }
};
