const translations = {
    'ua': {
        'header-title': 'Помічник для BAS v1.0',
        'btn-func': 'Функції 🛠️',
        'btn-lang-menu': 'МОВА 🌍',
        'btn-close': 'Закрити ❌',
        'btn-calc': 'Рахувати показники 📊',
        'btn-search': 'Шукати проблеми 🔍',
        'btn-ua': 'Українська 🇺🇦 ✅',
        'btn-en': 'English 🇺🇸',
                'btn-de': 'Deutsch 🇩🇪',
                'btn-pl': 'Polski 🇵🇱',
        'btn-back-func': 'НАЗАД ⬅️',
        'btn-back-lang': 'НАЗАД ⬅️',
        'loading': '⏳ Обробка...',
        'done': '✅ Готово!'
    },
    'en': {
        'header-title': 'Helper for BAS v1.0',
        'btn-func': 'Functions 🛠️',
        'btn-lang-menu': 'LANGUAGE 🌍',
        'btn-close': 'Close ❌',
        'btn-calc': 'Calculate metrics 📊',
        'btn-search': 'Search problems 🔍',
        'btn-ua': 'Ukrainian 🇺🇦',
        'btn-en': 'English 🇺🇸 ✅',
                'btn-de': 'German 🇩🇪',
                'btn-pl': 'Polish 🇵🇱',
        'btn-back-func': 'BACK ⬅️',
        'btn-back-lang': 'BACK ⬅️',
        'loading': '⏳ Processing...',
        'done': '✅ Done!'
    },
    'de': {
        'header-title': 'Helfer für BAS v1.0',
        'btn-func': 'Funktionen 🛠️',
        'btn-lang-menu': 'SPRACHE 🌍',
        'btn-close': 'Schließen ❌',
        'btn-calc': 'Metriken berechnen 📊',
        'btn-search': 'Probleme suchen 🔍',
        'btn-ua': 'Ukrainisch 🇺🇦',
        'btn-en': 'Englisch 🇺🇸',
        'btn-de': 'Deutsch 🇩🇪 ✅',
                'btn-pl': 'Polnisch 🇵🇱',
        'btn-back-func': 'ZURÜCK ⬅️',
        'btn-back-lang': 'ZURÜCK ⬅️',
        'loading': '⏳ Verarbeitung...',
        'done': '✅ Fertig!'
    },
    'pl': {
        'header-title': 'Pomocnik dla BAS v1.0',
        'btn-func': 'Funkcje 🛠️',
        'btn-lang-menu': 'JĘZYK 🌍',
        'btn-close': 'Zamknij ❌',
        'btn-calc': 'Oblicz wskaźniki 📊',
        'btn-search': 'Szukaj problemów 🔍',
        'btn-ua': 'Ukraiński 🇺🇦',
        'btn-en': 'Angielski 🇺🇸',
        'btn-de': 'Niemiecki 🇩🇪',
        'btn-pl': 'Polski 🇵🇱 ✅',
        'btn-back-func': 'WSTECZ ⬅️',
        'btn-back-lang': 'WSTECZ ⬅️',
        'loading': '⏳ Przetwarzanie...',
        'done': '✅ Gotowe!'
    }
};